### ISSUE TITLE
Filter newcomers for not being a Debian developer

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#18]
Right now, the person w/ email gcs@debian.org shows up in the newcomers dashboard. We should filter Debian developers out.

**Comment by daveeloo** [comment]
23:53       Boris Pek, 07/01/2013
23:53       He's showing up in newcomers
23:53       but He's a debian developer
23:53       Stephen Kitt, 05/05/2013
23:53       as well
23:54       also, looks like a buggy email - http://greenhouse-daveeloo.dotcloud.com/contributors/bottoms@debian.org.org

**Comment by daveeloo** [comment]
Added logic to build_people_db so that anyone with at debian email address is marked as a Debian developer. This will fix the problem for Boris Pek and gcs at debian.org. Also filtering out Debian developers from the first_timers view. Stephen Kitt is properly marked as a Debian developer and will be filtered out now. The problem with bottoms at debian.org.org is from bad UDD data.
