### ISSUE TITLE
Adding a "contact" leads to a 404

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#6]
When I:
- Visit http://greenhouse-daveeloo.dotcloud.com/
- Click on any name
- Enter text into the text field labeled "Record Contact"
- Hit "Record Contact"

the result seems to get saved, but I seem to get redirected to a URL like http://greenhouse-daveeloo.dotcloud.com/contributors/?c=3 which is a 404.

**Comment by andrewsomething** [comment]
Looking at `greenhouse/templates/person.html` on line 85 I see:

`<input type="hidden" name="next" value="/contributors/{{ person.lpid }}#" />`

I think you are using email addresses instead of lpid, so it should probably be:

`<input type="hidden" name="next" value="/contributors/{{ person.email }}#" />`

**Comment by paulproteus** [comment]
@daveeloo, do say thanks to nice people like @andrewsomething who help out by commenting on your bugs! (-:

**Comment by daveeloo** [comment]
@andrewsomething, thanks for your help!
